# Generated by Django 4.0.4 on 2022-04-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_day_user_alter_day_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='days',
        ),
        migrations.AddField(
            model_name='task',
            name='days',
            field=models.ManyToManyField(to='main_app.day'),
        ),
    ]
