# Generated by Django 4.0.4 on 2022-04-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_day_tasks_remove_task_days_task_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='days',
        ),
        migrations.AddField(
            model_name='day',
            name='tasks',
            field=models.ManyToManyField(to='main_app.task'),
        ),
    ]
