# Generated by Django 4.0.4 on 2022-04-27 01:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0010_alter_day_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('day', 'user')},
        ),
    ]
